### ISSUE TITLE
YAML 기본 프로파일 지정 방식 수정

### ISSUE THREAD

**Issue by yechanpark** [Pibotal/Friendly#2]
- 기존 : local + local에 대한 config에 대한 내용
 - 변경 : local 프로파일만지정, local에 대한 config 내용은 별도로 분리

**Comment by ehdrylang** [comment]
이슈 등록할 때, 템플릿이 있었으면 좋겠습니다.
어떤 문제를 어떻게 해결하고자 하는지 눈에 띄면 좋겠습니다.
적절한 오픈소스를 한 번 참고해서 공유해보도록 하시죠

**Comment by yechanpark** [comment]
@ehdrylang 
넵 템플릿은 적절한 구조를 생각한 뒤에 수정하도록 하겠습니다.
좋은 아이디어 있으면 공유 부탁드리겠습니다.

**Comment by ehdrylang** [comment]
개인적으로 '어떤 문제'가 있거나 예상되어 '어떻게 개선하려고 하는지'는 나왔으면 좋겠습니다.
아이디어는 오프라인 회의에서 만들어보는게 좋겠습니다.
